In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
plt.style.use('ggplot')
import seaborn as sns

## DataFrames

#### Archive of Games

In [68]:
raw_games = pd.read_csv('archive.csv')

In [69]:
raw_games.head()

,Unnamed: 0,season,week,game_date,game_time,home_team_id,home_team_stats_id,home_team_abbrev,visit_team_id,visit_team_stats_id,...,kickoff,month,start,score,total,spread,over_hit,under_hit,favorite_covered,underdog_covered
0,0,1983,1,1983-09-03 00:00:00,18,27,SF,SF,23,PHI,...,Sep 3 6:00 PM,September,Night,22-17,39,4.0,0,1,0,1
1,1,1983,1,1983-09-04 00:00:00,12,19,NO,NO,1,ARI,...,Sep 4 12:00 PM,September,Day,17-28,45,3.0,1,0,1,0
2,2,1983,1,1983-09-04 00:00:00,13,4,BUF,BUF,16,MIA,...,Sep 4 1:00 PM,September,Day,12-0,12,4.0,0,1,0,1
3,3,1983,1,1983-09-04 00:00:00,13,6,CHI,CHI,2,ATL,...,Sep 4 1:00 PM,September,Day,20-17,37,1.5,0,1,0,1
4,4,1983,1,1983-09-04 00:00:00,13,7,CIN,CIN,22,OAK,...,Sep 4 1:00 PM,September,Day,20-10,30,2.0,0,1,0,1

In [70]:
raw_games.columns

Index(['Unnamed: 0', 'season', 'week', 'game_date', 'game_time',
       'home_team_id', 'home_team_stats_id', 'home_team_abbrev',
       'visit_team_id', 'visit_team_stats_id', 'visit_team_abbrev',
       'home_team_score', 'visit_team_score', 'game_over_under', 'line',
       'surface', 'weather_icon', 'temperature', 'precip_probability',
       'precip_type', 'wind_speed', 'wind_bearing', 'name', 'kickoff', 'month',
       'start', 'score', 'total', 'spread', 'over_hit', 'under_hit',
       'favorite_covered', 'underdog_covered'],
      dtype='object')

In [71]:
raw_games.shape

(9113, 33)

In [72]:
raw_games.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9113 entries, 0 to 9112
Data columns (total 33 columns):
Unnamed: 0             9113 non-null int64
season                 9113 non-null int64
week                   9113 non-null int64
game_date              9113 non-null object
game_time              9113 non-null int64
home_team_id           9113 non-null int64
home_team_stats_id     9113 non-null object
home_team_abbrev       9113 non-null object
visit_team_id          9113 non-null int64
visit_team_stats_id    9113 non-null object
visit_team_abbrev      9113 non-null object
home_team_score        9113 non-null int64
visit_team_score       9113 non-null int64
game_over_under        9073 non-null float64
line                   9113 non-null float64
surface                9113 non-null object
weather_icon           6961 non-null object
temperature            6961 non-null float64
precip_probability     791 non-null object
precip_type            791 non-null object
wind_speed             6882 non-null float64
wind_bearing           6833 non-null float64
name                   9113 non-null object
kickoff                9113 non-null object
month                  9113 non-null object
start                  9098 non-null object
score                  9113 non-null object
total                  9113 non-null int64
spread                 9113 non-null float64
over_hit               9113 non-null int64
under_hit              9113 non-null int64
favorite_covered       9113 non-null int64
underdog_covered       9113 non-null int64
dtypes: float64(6), int64(13), object(14)
memory usage: 2.3+ MB

In [73]:
games = raw_games.copy()

#### Drop Unnecessary Columns

In [74]:
games.drop(['Unnamed: 0', 
       'home_team_id',  'home_team_abbrev',
       'visit_team_id',  'visit_team_abbrev',
        'precip_probability',
       'precip_type', 
        'spread','game_time'], axis = 1, inplace= True)

#### Standardize Columns to Merge Later

In [75]:
games.rename(columns={'game_date':'Date','home_team_stats_id':'Home Team', 'visit_team_stats_id':'Away Team'},inplace = True)

In [76]:
games

,season,week,Date,Home Team,Away Team,home_team_score,visit_team_score,game_over_under,line,surface,...,name,kickoff,month,start,score,total,over_hit,under_hit,favorite_covered,underdog_covered
0,1983,1,1983-09-03 00:00:00,SF,PHI,17,22,40.0,-4.0,Grass,...,PHI @ SF,Sep 3 6:00 PM,September,Night,22-17,39,0,1,0,1
1,1983,1,1983-09-04 00:00:00,NO,ARI,28,17,37.0,-3.0,Dome,...,SLC @ NO,Sep 4 12:00 PM,September,Day,17-28,45,1,0,1,0
2,1983,1,1983-09-04 00:00:00,BUF,MIA,0,12,36.0,4.0,Turf,...,MIA @ BUF,Sep 4 1:00 PM,September,Day,12-0,12,0,1,0,1
3,1983,1,1983-09-04 00:00:00,CHI,ATL,17,20,38.0,-1.5,Grass,...,ATL @ CHI,Sep 4 1:00 PM,September,Day,20-17,37,0,1,0,1
4,1983,1,1983-09-04 00:00:00,CIN,OAK,10,20,42.0,-2.0,Turf,...,LAD @ CIN,Sep 4 1:00 PM,September,Day,20-10,30,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9108,2018,19,2019-01-13 00:00:00,NE,LAC,41,28,47.5,-3.5,Turf,...,LAC @ NE,Jan 13 1:05 PM,January,Day,28-41,69,1,0,1,0
9109,2018,19,2019-01-13 00:00:00,NO,PHI,20,14,52.5,-8.5,Dome,...,PHI @ NO,Jan 13 4:35 PM,January,Late,14-20,34,0,1,0,1
9110,2018,20,2019-01-20 00:00:00,NO,LAR,23,26,55.0,-3.0,Dome,...,LAR @ NO,Jan 20 3:05 PM,January,Day,26-23,49,0,1,0,1
9111,2018,20,2019-01-20 00:00:00,KC,NE,31,37,56.0,-3.0,Grass,...,NE @ KC,Jan 20 6:40 PM,January,Night,37-31,68,1,0,0,1
9112,2018,21,2019-02-03 00:00:00,LAR,NE,3,13,55.5,-2.0,Dome,...,NE @ LAR,Feb 3 6:30 PM,February,Night,13-3,16,0,1,0,1

#### Handling NaNs

In [77]:
games.isnull().sum()

season                 0
week                   0
Date                   0
Home Team              0
Away Team              0
home_team_score        0
visit_team_score       0
game_over_under       40
line                   0
surface                0
weather_icon        2152
temperature         2152
wind_speed          2231
wind_bearing        2280
name                   0
kickoff                0
month                  0
start                 15
score                  0
total                  0
over_hit               0
under_hit              0
favorite_covered       0
underdog_covered       0
dtype: int64

In [78]:
games[games.surface == 'Dome'].shape

(2152, 24)

In [79]:
games.temperature.fillna(70,inplace =True)

In [80]:
games.weather_icon.fillna('Dome', inplace = True)

In [81]:
games.loc[(games.surface == 'Dome') & (games.wind_speed.isnull()),'wind_speed'] = 0

In [83]:
games.loc[(games.surface == 'Dome') & (games.wind_bearing.isnull()),'wind_bearing'] = 0

In [97]:
games.loc[(games.wind_speed.isnull()),'wind_speed'] = games.wind_speed.mean()

In [104]:
games.loc[(games.wind_bearing.isnull()),'wind_bearing'] = games.wind_bearing.mean()

In [90]:
games.start.fillna('Day',inplace = True)

In [107]:
games[games.game_over_under.isnull()]

,season,week,Date,Home Team,Away Team,home_team_score,visit_team_score,game_over_under,line,surface,...,name,kickoff,month,start,score,total,over_hit,under_hit,favorite_covered,underdog_covered
960,1987,3,1987-10-04 00:00:00,ATL,PIT,12,28,NaN,3.5,Grass,...,PIT @ ATL,Oct 4 1:00 PM,October,Day,28-12,40,1,0,0,1
961,1987,3,1987-10-04 00:00:00,BUF,IND,6,47,NaN,3.5,Turf,...,IND @ BUF,Oct 4 1:00 PM,October,Day,47-6,53,1,0,0,1
962,1987,3,1987-10-04 00:00:00,CIN,LAC,9,10,NaN,-2.0,Turf,...,SD @ CIN,Oct 4 1:00 PM,October,Day,10-9,19,1,0,0,1
963,1987,3,1987-10-04 00:00:00,DET,TB,27,31,NaN,2.0,Dome,...,TB @ DET,Oct 4 1:00 PM,October,Day,31-27,58,1,0,0,1
964,1987,3,1987-10-04 00:00:00,NE,CLE,10,20,NaN,-4.0,Turf,...,CLE @ NE,Oct 4 1:00 PM,October,Day,20-10,30,1,0,0,1
965,1987,3,1987-10-04 00:00:00,NO,LAR,37,10,NaN,-5.0,Dome,...,LAR @ NO,Oct 4 1:00 PM,October,Day,10-37,47,1,0,1,0
966,1987,3,1987-10-04 00:00:00,PHI,CHI,3,35,NaN,2.0,Turf,...,CHI @ PHI,Oct 4 1:00 PM,October,Day,35-3,38,1,0,0,1
967,1987,3,1987-10-04 00:00:00,WAS,ARI,28,21,NaN,5.0,Grass,...,SLC @ WAS,Oct 4 1:00 PM,October,Day,21-28,49,1,0,1,0
968,1987,3,1987-10-04 00:00:00,DEN,TEN,10,40,NaN,-7.0,Grass,...,HOO @ DEN,Oct 4 4:00 PM,October,Late,40-10,50,1,0,0,1
969,1987,3,1987-10-04 00:00:00,OAK,KC,35,17,NaN,-7.5,Grass,...,KC @ LAD,Oct 4 4:00 PM,October,Late,17-35,52,1,0,1,0
970,1987,3,1987-10-04 00:00:00,MIN,GB,16,23,NaN,3.5,Dome,...,GB @ MIN,Oct 4 4:00 PM,October,Late,23-16,39,1,0,0,1
971,1987,3,1987-10-04 00:00:00,NYJ,DAL,24,38,NaN,7.5,Turf,...,DAL @ NYJ,Oct 4 4:00 PM,October,Late,38-24,62,1,0,0,1
972,1987,3,1987-10-04 00:00:00,SEA,MIA,24,20,NaN,3.0,Dome,...,MIA @ SEA,Oct 4 4:00 PM,October,Late,20-24,44,1,0,1,0
973,1987,3,1987-10-05 00:00:00,NYG,SF,21,41,NaN,7.5,Turf,...,SF @ NYG,Oct 5 9:00 PM,October,Night,41-21,62,1,0,0,1
974,1987,4,1987-10-11 00:00:00,CHI,MIN,27,7,NaN,-18.0,Grass,...,MIN @ CHI,Oct 11 1:00 PM,October,Day,7-27,34,1,0,1,0
975,1987,4,1987-10-11 00:00:00,CLE,TEN,10,15,NaN,-2.5,Grass,...,HOO @ CLE,Oct 11 1:00 PM,October,Day,15-10,25,1,0,0,1
976,1987,4,1987-10-11 00:00:00,DAL,PHI,41,22,NaN,-21.5,Turf,...,PHI @ DAL,Oct 11 1:00 PM,October,Day,22-41,63,1,0,0,1
977,1987,4,1987-10-11 00:00:00,GB,DET,16,19,NaN,-7.0,Grass,...,DET @ GB,Oct 11 1:00 PM,October,Day,19-16,35,1,0,0,1
978,1987,4,1987-10-11 00:00:00,IND,NYJ,6,0,NaN,-11.0,Dome,...,NYJ @ IND,Oct 11 1:00 PM,October,Day,0-6,6,1,0,0,1
979,1987,4,1987-10-11 00:00:00,MIA,KC,42,0,NaN,-9.5,Grass,...,KC @ MIA,Oct 11 1:00 PM,October,Day,0-42,42,1,0,1,0
980,1987,4,1987-10-11 00:00:00,NE,BUF,14,7,NaN,-10.5,Turf,...,BUF @ NE,Oct 11 1:00 PM,October,Day,7-14,21,1,0,0,1
981,1987,4,1987-10-11 00:00:00,ARI,NO,24,19,NaN,-2.5,Grass,...,NO @ SLC,Oct 11 1:00 PM,October,Day,19-24,43,1,0,1,0
982,1987,4,1987-10-11 00:00:00,TB,LAC,13,17,NaN,-3.0,Grass,...,SD @ TB,Oct 11 1:00 PM,October,Day,17-13,30,1,0,0,1
983,1987,4,1987-10-11 00:00:00,ATL,SF,17,25,NaN,23.0,Grass,...,SF @ ATL,Oct 11 4:00 PM,October,Late,25-17,42,1,0,1,0
984,1987,4,1987-10-11 00:00:00,LAR,PIT,31,21,NaN,3.5,Grass,...,PIT @ LAR,Oct 11 4:00 PM,October,Late,21-31,52,1,0,1,0
985,1987,4,1987-10-11 00:00:00,NYG,WAS,12,38,NaN,10.5,Turf,...,WAS @ NYG,Oct 11 4:00 PM,October,Late,38-12,50,1,0,0,1
986,1987,4,1987-10-11 00:00:00,SEA,CIN,10,17,NaN,-7.0,Dome,...,CIN @ SEA,Oct 11 4:00 PM,October,Late,17-10,27,1,0,0,1
988,1987,5,1987-10-18 00:00:00,ATL,LAR,24,20,NaN,12.5,Grass,...,LAR @ ATL,Oct 18 1:00 PM,October,Day,20-24,44,1,0,1,0
989,1987,5,1987-10-18 00:00:00,CHI,NO,17,19,NaN,-5.5,Grass,...,NO @ CHI,Oct 18 1:00 PM,October,Day,19-17,36,1,0,0,1
990,1987,5,1987-10-18 00:00:00,CIN,CLE,0,34,NaN,5.0,Turf,...,CLE @ CIN,Oct 18 1:00 PM,October,Day,34-0,34,1,0,0,1
991,1987,5,1987-10-18 00:00:00,DET,SEA,14,37,NaN,3.0,Dome,...,SEA @ DET,Oct 18 1:00 PM,October,Day,37-14,51,1,0,0,1
992,1987,5,1987-10-18 00:00:00,GB,PHI,16,10,NaN,-6.5,Grass,...,PHI @ GB,Oct 18 1:00 PM,October,Day,10-16,26,1,0,0,1
993,1987,5,1987-10-18 00:00:00,TEN,NE,7,21,NaN,-6.0,Dome,...,NE @ HOO,Oct 18 1:00 PM,October,Day,21-7,28,1,0,0,1
994,1987,5,1987-10-18 00:00:00,NYJ,MIA,37,31,NaN,3.0,Turf,...,MIA @ NYJ,Oct 18 1:00 PM,October,Day,31-37,68,1,0,1,0
995,1987,5,1987-10-18 00:00:00,PIT,IND,21,7,NaN,-11.5,Turf,...,IND @ PIT,Oct 18 1:00 PM,October,Day,7-21,28,1,0,1,0
996,1987,5,1987-10-18 00:00:00,TB,MIN,20,10,NaN,-5.5,Grass,...,MIN @ TB,Oct 18 1:00 PM,October,Day,10-20,30,1,0,1,0
997,1987,5,1987-10-18 00:00:00,BUF,NYG,6,3,NaN,4.0,Turf,...,NYG @ BUF,Oct 18 4:00 PM,October,Late,3-6,9,1,0,1,0
998,1987,5,1987-10-18 00:00:00,KC,DEN,17,26,NaN,12.0,Turf,...,DEN @ KC,Oct 18 4:00 PM,October,Late,26-17,43,1,0,1,0
999,1987,5,1987-10-18 00:00:00,OAK,LAC,17,23,NaN,-11.5,Grass,...,SD @ LAD,Oct 18 4:00 PM,October,Late,23-17,40,1,0,0,1
1000,1987,5,1987-10-18 00:00:00,SF,ARI,34,28,NaN,-13.5,Grass,...,SLC @ SF,Oct 18 4:00 PM,October,Late,28-34,62,1,0,0,1

In [113]:
games.dropna(inplace =True)

In [114]:
games.shape

(9073, 24)

#### Betting Odds

In [ ]:
xls = pd.ExcelFile('nfl.xlsx')
raw_odds = pd.read_excel(xls, 0)

In [ ]:
raw_odds.shape

In [ ]:
raw_odds.head()

#### Standardize Team Names to Merge Later

In [ ]:
raw_odds['Home Team'].unique()

In [ ]:
games['Home Team'].unique()

In [ ]:
lst =  ['Kansas City Chiefs', 'San Francisco 49ers', 'Green Bay Packers',
       'Baltimore Ravens', 'Philadelphia Eagles', 'New Orleans Saints',
       'New England Patriots', 'Houston Texans', 'Seattle Seahawks',
       'Denver Broncos', 'Los Angeles Rams', 'Buffalo Bills',
       'Carolina Panthers', 'Cincinnati Bengals', 'Dallas Cowboys',
       'Detroit Lions', 'Jacksonville Jaguars', 'Minnesota Vikings',
       'New York Giants', 'Tampa Bay Buccaneers', 'Chicago Bears',
       'Los Angeles Chargers', 'Atlanta Falcons', 'Cleveland Browns',
       'Indianapolis Colts', 'Miami Dolphins', 'New York Jets',
       'Tennessee Titans', 'Washington Redskins', 'Pittsburgh Steelers',
       'Arizona Cardinals', 'Oakland Raiders', 'San Diego Chargers',
       'St. Louis Rams']
lst.sort()

In [ ]:
lst2 = ['SF', 'NO', 'BUF', 'CHI', 'CIN', 'CLE', 'TEN', 'NE', 'NYG', 'PIT',
       'TB', 'KC', 'LAC', 'WAS', 'MIN', 'ATL', 'DET', 'GB', 'PHI', 'ARI',
       'IND', 'OAK', 'LAR', 'MIA', 'NYJ', 'DAL', 'DEN', 'SEA', 'JAX',
       'CAR', 'BAL', 'HOU']
lst2.sort()

In [ ]:
lst.index('Pittsburgh Steelers')

In [ ]:
dictionary = dict(zip(lst[:27],lst2[:27]))

In [ ]:
dictionary.update({'San Diego Chargers': 'LAC', 'San Francisco 49ers': 'SF', 'Seattle Seahawks':'SEA', 'St.Louis Rams': 'LAR','Tampa Bay Buccaneers':'TB', 'Tennessee Titans': 'TEN','Washington Redskins':'WAS'})

In [ ]:
odds = raw_odds.copy()

In [ ]:
odds.replace(dictionary, inplace = True)

In [ ]:
odds.head()

#### Drop Unecessary Columns

In [ ]:
odds.columns

In [ ]:
odds.drop(['Home Score', 'Away Score',
           'Overtime?', 'Playoff Game?', 'Neutral Venue?', 'Home Odds Open',
            'Away Odds Open','Home Line Min', 'Home Line Max', 'Home Line Close','Home Line Open',
           'Away Line Open','Away Line Min', 'Away Line Max', 'Away Line Close','Home Line Odds Open', 'Away Line Odds Open',  'Total Score Open',
           'Total Score Over Open',  'Total Score Under Open','Total Score Min', 'Total Score Max', 'Total Score Close',
           'Notes'] , axis = 1, inplace = True)

In [ ]:
min_odds_lst = [col for col in odds.columns[2:] if 'Min' in col]
min_odds_lst

In [ ]:
max_odds_lst = [col for col in odds.columns[2:] if 'Max' in col]
max_odds_lst

#### Make Range of Odds Columns

In [ ]:
def range_of_odds(df, col_1,col_2, type_of_odds):
    df[type_of_odds+' Range'] = abs(df[col_1]-df[col_2])

In [ ]:
min_max_odds_lst = list(zip(min_odds_lst, max_odds_lst))
col_names = ['Home Odds', 'Away Odds', 'Home Line Odds', 'Away Line Odds', 'Total Score Over Odds', 'Total Score Under Odds']
for i in range(len(min_max_odds_lst)):
    range_of_odds(odds, min_max_odds_lst[i][0],min_max_odds_lst[i][1], col_names[i])

In [ ]:
odds.columns

In [ ]:
odds.head()

#### Drop Columns After Range Columns Made

In [ ]:
min_odds_lst.extend(max_odds_lst)

In [ ]:
odds.drop(min_odds_lst, axis = 1, inplace = True)

In [ ]:
odds.head()

In [ ]:
odds

In [ ]:
games['Date']= pd.to_datetime(games['Date'])

In [ ]:
games_and_odds = pd.merge(games,odds, on = ['Date','Home Team','Away Team'], how = 'left')

In [ ]:
games_and_odds.tail()

In [ ]:
games_and_odds.columns

In [ ]:
games_and_odds.wind_bearing.isnull().sum()

In [ ]:
games_and_odds.wind_speed.isnull().sum()

In [ ]:
games_and_odds[games_and_odds.surface == 'Dome']['wind_speed'].isnull().sum()